### PR TITLE
Implement "Skipped" tests, improve Junit report

### PR DESCRIPTION
**Pull request by nacho4d**
Hello

In Xcode11.4 there is a new XCTSkipIf() XCTSkipUnless() apis that allow to skips in tests and this is reflected as gray records in test view. 

In this PR I have:
- Implemented "Skipped" tests in html and junit reporter.
- Fixed in junit reporter so failures are correctly written to the xml.
- Upgraded project to Xcode11.4 In order to use XCTSkipIf, etc.
- Upgraded XCResultKit to 0.6.0 because of Xcode11.4

Here is a couple of screenshots of the new Skipped tab:
Screen Shot 2020-04-21 at 4 24 23
Screen Shot 2020-04-21 at 4 24 42

I hope this is welcomed and it gets merged sometime soon.

### CODE REVIEW

**Comment by nacho4d** [comment]
Here are some screenshot of a bit old gitlab instance that uses the junit reports to show failures in merge request pages. (It demostrates junit reporter works ok)

gitlab_11_b
gitlab_11_a

**Comment by nacho4d** [comment]
I wanted to implement some unit testes but currently there is no base code for that. I have an idea:

- build sample app and create `xctestresult/` and copy it somewhere below `test` directory.
- Create some unit tests from that data.

If you think this idea is OK I can implement some tests.

Hope this PR lands soon. 

Thanks for this!

**Comment by nacho4d** [comment]
@@TitouanVanBelle Can you take a look at this please? :)

**Comment by SergiiVashchenko** [comment]
@TitouanVanBelle it really would be great to show "Skipped" tests in the report as well. Could you please take a look at the PR?

**Comment by nacho4d** [comment]
@TitouanVanBelle Thanks for merging!

**Pull request merged**
