### PR TITLE
Update XCResultKit / Removed Darwin dependency / Update sample app

### PR DESCRIPTION
**Pull request by nacho4d**
- Updated XCResultKit from 7.1 to 0.9.2
- Replaced one `import Darwin` with `import Foundation` (Fixes https://github.com/TitouanVanBelle/XCTestHTMLReport/pull/195) 
- Sample App: Rename "XCTestHTMLReportSampleApp" to "Sample" app to simplify things (easier to browse in smalls screens). I didn't rename root folder because I wanted XCTestHTMLReportSampleApp to show at the end since it is just not the main part of this tool.
- Added 1024 icon to fix warning in sample app.

### CODE REVIEW

**Comment by nacho4d** [comment]
@TitouanVanBelle @chrisballinger 
Hello. Could you review this PR please?

**Comment by anuragmaheshwari** [comment]
@nacho4d Would this solve this issue https://github.com/TitouanVanBelle/XCTestHTMLReport/issues/208?

**Comment by AleksPetrovski** [comment]
@anuragmaheshwari yes, this PR will fix issue #208.
I just checked out PR and compiled/installed `xchtmlreport`, then executed fastlane line and was able to see generated test report with actual tests in it.
great work @nacho4d!

@TitouanVanBelle @chrisballinger could you please review this PR.
Thanks in advance!

**Comment by nacho4d** [comment]
@TitouanVanBelle Hello, Could you merge this please?

**Review by anuragmaheshwari — APPROVED** [review]

**Pull request merged**
